REPOSITORY_URL=https://repository.exoplatform.org/content/repositories/exo-private-snapshots
REPOSITORY_USERNAME=${REPOSITORY_USERNAME:?UNSET}
REPOSITORY_PASSWORD=${REPOSITORY_PASSWORD:?UNSET}
PLF_ARTIFACT_GROUPID=${PLF_ARTIFACT_GROUPID:?UNSET}
PLF_ARTIFACT_ARTIFACTID=${PLF_ARTIFACT_ARTIFACTID:?UNSET}
VERSION=${VERSION:?UNSET}
PLF_ARTIFACT_PACKAGING=zip
PLF_ARTIFACT_CLASSIFIER=
DL_DIR=/tmp/download
PLF_NAME=tqa-poc

PLF_SRV_DIR=/tmp/srv

DEPLOYMENT_MYSQL_DRIVER_VERSION=5.1.25
